In [1]:
import tensorflow as tf
tf.__version__

'2.2.0'

## 1. 创建

In [2]:
## constant, range

x = tf.constant(range(12))
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [3]:
x.shape # 形状

TensorShape([12])

In [4]:
len(x) # element总数

12

In [5]:
## reshape

X = tf.reshape(x,(3,4))
X

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [6]:
## zeros

tf.zeros((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [7]:
## ones

tf.ones((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [8]:
## constant, list

Y = tf.constant([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
Y

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]], dtype=int32)>

In [9]:
## tf.random.normal

tf.random.normal(shape=[3,4], mean=0, stddev=1)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.33045727,  0.01690212,  0.05739298,  1.1341798 ],
       [ 3.0322042 , -0.17056434,  0.02937704, -0.48972338],
       [ 0.571351  ,  0.8677396 ,  0.07496562,  0.6594578 ]],
      dtype=float32)>

## 2. 运算

In [10]:
X, Y

(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=int32)>,
 <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]], dtype=int32)>)

In [11]:
## add

X + Y

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 2,  2,  6,  6],
       [ 5,  7,  9, 11],
       [12, 12, 12, 12]], dtype=int32)>

In [12]:
## multiply

X * Y

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  8,  9],
       [ 4, 10, 18, 28],
       [32, 27, 20, 11]], dtype=int32)>

In [13]:
## division

X / Y

<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[ 0.  ,  1.  ,  0.5 ,  1.  ],
       [ 4.  ,  2.5 ,  2.  ,  1.75],
       [ 2.  ,  3.  ,  5.  , 11.  ]])>

In [14]:
## exp

Y = tf.cast(Y, tf.float32)
tf.exp(Y)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 7.389056 ,  2.7182817, 54.598152 , 20.085537 ],
       [ 2.7182817,  7.389056 , 20.085537 , 54.598152 ],
       [54.59815  , 20.085537 ,  7.389056 ,  2.7182817]], dtype=float32)>

In [15]:
## matmul

Y = tf.cast(Y, tf.int32)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 18,  20,  10],
       [ 58,  60,  50],
       [ 98, 100,  90]], dtype=int32)>

In [16]:
## concat

tf.concat([X,Y], axis=0)

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 2,  1,  4,  3],
       [ 1,  2,  3,  4],
       [ 4,  3,  2,  1]], dtype=int32)>

In [17]:
## concat

tf.concat([X,Y], axis=1)

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  2,  1,  4,  3],
       [ 4,  5,  6,  7,  1,  2,  3,  4],
       [ 8,  9, 10, 11,  4,  3,  2,  1]], dtype=int32)>

In [18]:
## equal

tf.equal(X,Y)

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])>

In [19]:
## reduce_sum

tf.reduce_sum(X)

<tf.Tensor: shape=(), dtype=int32, numpy=66>

In [20]:
## norm

X = tf.cast(X, tf.float32)
tf.norm(X)

<tf.Tensor: shape=(), dtype=float32, numpy=22.494444>

## 3. 广播

In [21]:
A = tf.reshape(tf.constant(range(3)), shape=(3,1))
B = tf.reshape(tf.constant(range(2)), shape=(1,2))
A, B

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>)

In [22]:
A + B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]], dtype=int32)>

## 4. 索引/切片

In [23]:
X

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [24]:
X[-1]

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>

In [25]:
X[1:3]

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [26]:
X = tf.Variable(X)
X

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [27]:
X[1,2].assign(9)

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [28]:
X[1:2,:].assign(tf.ones(X[1:2,:].shape, dtype=tf.float32)*12)

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

## 5. 节省空间

In [29]:
X = tf.Variable(X)
Y = tf.cast(Y, dtype=tf.float32)

before = id(Y)  # 指针
Y = Y + X
id(Y) == before # False, 说明经过求和运算后，指针位置变化

False

In [30]:
## assign

Z = tf.Variable(tf.zeros_like(Y))
before = id(Z)
Z[:].assign(X + Y)
id(Z) == before

True

In [31]:
Z = tf.add(X,Y)
id(Z) == before

False

In [32]:
## assign_add

before = id(X)
X.assign_add(Y)
id(X) == before

True

## 6. tensor & numpy array

In [33]:
import numpy as np

In [34]:
## numpy array --> tensor

p = np.ones(shape=(2,3))
d = tf.constant(p)
d

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [35]:
## tensor --> numpy array

np.array(d)

array([[1., 1., 1.],
       [1., 1., 1.]])