## 0. 创建数据集

In [1]:
import os

os.makedirs(os.path.join('../..','data'),exist_ok=True)
data_file = os.path.join('../..','data','house_timy.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # column name
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

## 1. 加载数据

In [2]:
import pandas as pd

data_file = os.path.join('../..','data','house_timy.csv')
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


## 2. 缺失值处理

In [3]:
inputs, outputs = data.iloc[:,0:2], data.iloc[:,2]

In [4]:
## 连续型特征

inputs = inputs.fillna(inputs.mean())
inputs

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [5]:
## 离散型特征

inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

## 3. 转换为张量

In [6]:
import tensorflow as tf

x,y = tf.constant(inputs.values), tf.constant(outputs.values)
x, y

(<tf.Tensor: shape=(4, 3), dtype=float64, numpy=
 array([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]])>,
 <tf.Tensor: shape=(4,), dtype=int64, numpy=array([127500, 106000, 178100, 140000])>)