In [1]:
import tensorflow as tf

## 1. 标量

In [2]:
x = tf.constant([3.0])
y = tf.constant([2.0])

In [3]:
x + y

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([5.], dtype=float32)>

In [4]:
x * y

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([6.], dtype=float32)>

In [5]:
x / y

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.5], dtype=float32)>

In [6]:
x ** y

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([9.], dtype=float32)>

## 2. 向量

In [7]:
x = tf.range(4)
x

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

In [8]:
x[3]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [9]:
x.shape

TensorShape([4])

In [10]:
len(x)

4

## 3. 矩阵

In [11]:
## range

A = tf.reshape(tf.range(20), shape=(5,4))
A

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]], dtype=int32)>

In [12]:
tf.transpose(A)

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]], dtype=int32)>

In [13]:
## list

B = tf.constant([[1,2,3],[2,0,4],[3,4,5]])
B

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 0, 4],
       [3, 4, 5]], dtype=int32)>

In [14]:
B == tf.transpose(B)

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

## 4. 张量

In [15]:
A = tf.reshape(tf.range(20), shape=(5,4))
A

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]], dtype=int32)>

In [16]:
B = A
B

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]], dtype=int32)>

In [17]:
A + B

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38]], dtype=int32)>

In [18]:
## A⊙B, 哈达玛积

A * B

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]], dtype=int32)>

In [19]:
## 标量 & 向量
a = 2
X = tf.reshape(tf.range(24), shape=(2,3,4))
X

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

In [20]:
a + X

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]],

       [[14, 15, 16, 17],
        [18, 19, 20, 21],
        [22, 23, 24, 25]]], dtype=int32)>

In [21]:
(a * X).shape

TensorShape([2, 3, 4])

## 5. 求和

### 5.1 向量

In [22]:
x = tf.range(4, dtype=tf.float32)
x

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>

In [23]:
## reduce_sum

tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

### 5.2 矩阵

In [24]:
A, A.shape

(<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]], dtype=int32)>,
 TensorShape([5, 4]))

In [25]:
## reduce_sum

tf.reduce_sum(A), tf.reduce_sum(A, axis=[0,1])

(<tf.Tensor: shape=(), dtype=int32, numpy=190>,
 <tf.Tensor: shape=(), dtype=int32, numpy=190>)

In [26]:
## reduce_sum, axis=0

A_sum_axis0 = tf.reduce_sum(A, axis=0)
A_sum_axis0, A_sum_axis0.shape

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([40, 45, 50, 55], dtype=int32)>,
 TensorShape([4]))

In [27]:
## reduce_sum, axis=1

A_sum_axis1 = tf.reduce_sum(A, axis=1)
A_sum_axis1, A_sum_axis1.shape

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 6, 22, 38, 54, 70], dtype=int32)>,
 TensorShape([5]))

In [28]:
## reduce_mean

tf.reduce_mean(tf.cast(A, dtype=tf.float32)), tf.reduce_sum(A)/tf.size(A).numpy()

(<tf.Tensor: shape=(), dtype=float32, numpy=9.5>,
 <tf.Tensor: shape=(), dtype=float64, numpy=9.5>)

In [29]:
## reduce_mean, axis=0

tf.reduce_mean(A, axis=0), tf.reduce_sum(A, axis=0)/A.shape[0]

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 8,  9, 10, 11], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 8.,  9., 10., 11.])>)

In [30]:
## reduce_sum, axis=1, keepdims, to broadcast

sum_A = tf.reduce_sum(A, axis=1, keepdims=True)
sum_A

<tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[ 6],
       [22],
       [38],
       [54],
       [70]], dtype=int32)>

In [31]:
## broadcast

A / sum_A

<tf.Tensor: shape=(5, 4), dtype=float64, numpy=
array([[0.        , 0.16666667, 0.33333333, 0.5       ],
       [0.18181818, 0.22727273, 0.27272727, 0.31818182],
       [0.21052632, 0.23684211, 0.26315789, 0.28947368],
       [0.22222222, 0.24074074, 0.25925926, 0.27777778],
       [0.22857143, 0.24285714, 0.25714286, 0.27142857]])>

## 6. 点积

In [32]:
x = tf.range(4, dtype=tf.float32)
y = tf.ones(4, dtype=tf.float32)
x, y

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>)

In [33]:
## tf.tensordot

tf.tensordot(x, y, axes=1)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [34]:
tf.reduce_sum(x * y)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

## 7. 矩阵-向量乘积

In [35]:
A = tf.cast(A, tf.float32)
A

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]], dtype=float32)>

In [36]:
x

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>

In [37]:
tf.linalg.matvec(A, x)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 14.,  38.,  62.,  86., 110.], dtype=float32)>

## 8. 矩阵-矩阵乘积

In [38]:
A

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]], dtype=float32)>

In [39]:
B = tf.ones(shape=(4,3), dtype=tf.float32)
B

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [40]:
tf.matmul(A, B)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[ 6.,  6.,  6.],
       [22., 22., 22.],
       [38., 38., 38.],
       [54., 54., 54.],
       [70., 70., 70.]], dtype=float32)>

## 9. 范数

In [41]:
u = tf.constant([3.0, -4.0])
u

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 3., -4.], dtype=float32)>

### 9.1 向量

In [42]:
## L2范数 = (sum(xi^2))^0.5

tf.norm(u)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [43]:
## L1范数 = sum(|xi|)

tf.reduce_sum(tf.abs(u))

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

### 9.2 矩阵

In [44]:
## 矩阵的Frobenius范数 （类似于向量的L2范数）

tf.norm(tf.ones(shape=(4,9)))

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>